services:
  postgres:
    image: postgres:17-alpine
    container_name: fullstackopen-postgres
    environment:
      POSTGRES_USER: nick
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: fullstackopen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
